FROM spotify/kafka

MAINTAINER Jeff Haynie <jhaynie@gmail.com>

ENV GWK_VERSION 1.0.0
ENV GWK_URL https://github.com/jhaynie/github-webhook-kafka/releases/download/"$GWK_VERSION"/github-webhook-kafka-linux-"$GWK_VERSION"

RUN mkdir -p /app

RUN wget -q $GWK_URL -O /app/github-webhook-kafka && \
	chmod +x /app/github-webhook-kafka

EXPOSE 2181 9092 8000

ENV AUTO_CREATE_TOPICS true

RUN echo "[program:github-webhook-kafka]\ncommand=/app/github-webhook-kafka\nautostart=true\nautorestart=true\n" > /etc/supervisor/conf.d/github-webhook-kafka.conf
